create-rootfs - added some checks for apps we need to create the isos

diff --git a/bin/create-rootfs b/bin/create-rootfs
--- a/bin/create-rootfs
+++ b/bin/create-rootfs
@@ -9,6 +9,16 @@ if [ "$(id -u)" -ne 0 ]; then
 	exit 1
 fi
 
+if [ ! -e /usr/bin/mksquashfs ]; then
+	echo "mksquashfs is missing"
+	exit 1
+}
+
+if [ ! -e /usr/bin/xorriso ]; then
+	echo "xorriso is missing"
+	exit 1
+fi
+
 if [ "$FVBE_ROOTFS_REPOSITORY" = "current" ]; then
   FDB=frugalware-current.fdb
   MIRROR="http://ftp.frugalware.org/pub/frugalware/frugalware-current/frugalware-$FVBE_ARCH"
