init: trap err/exit so it shows up in the log how we came to exit qemu

diff --git a/bin/init b/bin/init
--- a/bin/init
+++ b/bin/init
@@ -1,10 +1,19 @@
 #!/bin/sh
 
-error()
+bad_exit()
 {
-  echo "$1"
+  echo "Build has failed!"
   qemu-exit
 }
+
+good_exit()
+{
+  echo "Build has finished!"
+  qemu-exit
+}
+
+trap bad_exit ERR
+trap good_exit EXIT
 
 ROOT="/root"
 PATH="/sbin:/usr/sbin:/bin:/usr/bin"
@@ -12,25 +21,28 @@ PATH="/sbin:/usr/sbin:/bin:/usr/bin"
 export PATH
 
 if ! test -c /dev/zero; then
-	mount -t devtmpfs none /dev
-	test "$?" -ne 0 && error "Failed to mount /dev"
+  mount -t devtmpfs none /dev
 fi
 
 if ! test -d /sys/kernel; then
-	mount -t sysfs none /sys
-	test "$?" -ne 0 && error "Failed to mount /sys"
+  mount -t sysfs none /sys
 fi
 
 if ! test -d /proc/self; then
   mount -t proc none /proc
-	test "$?" -ne 0 && error "Failed to mount /proc"
 fi
 
 if ! test -d "$ROOT"; then
-	mkdir -p -m 0755 "$ROOT"
-	test "$?" -ne 0 && error "Failed to create $ROOT"
+  mkdir -p -m 0755 "$ROOT"
 fi
 
-bash
+if ! test -d /dev/pts; then
+  mkdir -p -m 0755 /dev/pts
+  mount -t devpts -o gid=5,mode=620 none /dev/pts
+fi
 
-qemu-exit
+if ! test -d /dev/shm; then
+  mkdir -p -m 0755 /dev/shm
+  mount -t tmpfs none /dev/shm
+fi
+
